version: '3.8'
services:
  frontend:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
       - ./frontend:/usr/share/nginx/html
       - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - backend-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - data-service
    env_file:
      - .env
    networks:
      - backend-network

  data-service:
    build: ./data-service
    ports:
      - "5001:5001"
    volumes:
      - ./data-service:/app
    networks:
      - backend-network

  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend-network

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge

volumes:
  db_data: