# Utilise l'image Python officielle
FROM python:3.9-slim

# Crée le répertoire de l'application
WORKDIR /app

# Copie les fichiers de requirements d'abord pour exploiter le cache Docker
COPY requirements.txt .

# Installe les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copie le reste de l'application
COPY . .

# Expose le port 5000 (port par défaut de Flask)
EXPOSE 5000

# Commande pour lancer l'application
CMD ["python", "app.py"]